### ISSUE TITLE
Unit tests are failing

### ISSUE THREAD

**Issue by valosekj** [ivadomed/MetricsReloaded#18]
After proposing some new changes in https://github.com/ivadomed/MetricsReloaded/pull/17, I noticed that unit tests are failing.

The reason is these two commits https://github.com/ivadomed/MetricsReloaded/commit/54ead73c0bd1fa16cb68946eb288a63ee76a5ae9 and https://github.com/ivadomed/MetricsReloaded/commit/2bad1f2115687871ac8c194fb5d222ba65de1d69 from @naga-karthik pushed directly to `main`.  @naga-karthik, it seems these two commits are specific to your MS lesion project. Maybe you can create a new branch with these two commits, and I will revert them from `main` to unit tests working.

**Comment by naga-karthik** [comment]
ah man, thanks for catching this! yeah I remember pushing directly to `main`, I am going to change it

**Comment by naga-karthik** [comment]
hey Jan, I looked at these commits. I believe commit https://github.com/ivadomed/MetricsReloaded/commit/54ead73c0bd1fa16cb68946eb288a63ee76a5ae9 was a hasty fix to test something quick and I should have reverted it back. This commit skips the cases where EmptyRef and EmptyPred are true (i.e. the model has learned correctly and the Dice=1). I wanted to compare ANIMA and MetricsReloaded to ensure that the metrics are computed correctly (i.e. the results match in both ways of computing metrics). 

Now, this commit can be reverted without having it another branch because this is precisely what we use MetricsReloaded for -- to not skip cases where GT is empty.

**Comment by naga-karthik** [comment]
As for commit https://github.com/ivadomed/MetricsReloaded/commit/2bad1f2115687871ac8c194fb5d222ba65de1d69, I see that the condition is commented out. I believe that was also to test something quick and should have been reverted back. I confirm the correct version is indeed seen in my [branch](https://github.com/ivadomed/MetricsReloaded/blob/nk/update-lesion-f1-metric/compute_metrics_reloaded.py#L180-L190) (i.e. where it is _not_ commented).

**Comment by naga-karthik** [comment]
I did `git reset --hard` to commit 76dbb55, please let me know if: (1) this is right thing to do? (2) should add revert commits instead?

**Comment by valosekj** [comment]
Thanks, Naga!

Yes, I believe you can run the following two commands on your local `main`:

```console
git reset --hard 76dbb55
git push --force
```

**Comment by naga-karthik** [comment]
thanks for the `git push --force`, Jan! I was missing this part! I am getting this error 

```
remote: - Cannot force-push to this branch
```

[This](https://stackoverflow.com/questions/59828481/developer-unable-to-push-to-protected-branch-after-git-reset) says that we need to `allow force pushes` from the Settings on Github. Do you have access by any chance?

**Comment by naga-karthik** [comment]
Merci, Jan! ❤️ 

Sorry for the mess, I will careful with the `main` branch in the future. I recall the changes were quite "urgent".
